import os
import sys
import argparse
import codecs
import pprint

from typing import Any, Dict, List, Tuple, Optional

import yaml

from ..util import print_info, print_error, ensure_dir
from .py_to_yaml import _KEY_TO_SECTION


_SECTION_TO_KEY = dict()
for _flat_key, (_section, _sub_key) in _KEY_TO_SECTION.items():
    _SECTION_TO_KEY[(_section, _sub_key)] = _flat_key


_STR_FLAT_KEYS = {
        'structure', 'structure_name',
        'diameter', 'size', 'gap', 'rounding', 'roundings', 'mesh_density',
        'core_size', 'shell_layers', 'offset',
        'tilt_angle', 'tilt_axis', 'rotation_angle',
        'n_spheres', 'shape_file', 'voxel_size', 'voxel_method',
        'refine',
        'materials', 'medium', 'substrate', 'use_substrate',
        'refractive_index_paths'}


_SIM_FLAT_KEYS = {
        'simulation_type', 'excitation_type',
        'wavelength_range',
        'polarizations', 'propagation_dirs',
        'dipole_position', 'dipole_moment',
        'impact_parameter', 'beam_energy', 'beam_width',
        'interp', 'relcutoff', 'waitbar',
        'calculate_cross_sections', 'calculate_fields',
        'field_region', 'field_mindist', 'field_nmax',
        'field_wavelength_idx', 'export_field_arrays',
        'field_hotspot_count', 'field_hotspot_min_distance',
        'use_parallel', 'num_workers', 'max_comp_threads',
        'wavelength_chunk_size',
        'use_mirror_symmetry', 'use_iterative_solver', 'use_nonlocality',
        'use_h2_compression',
        'output_dir', 'output_formats',
        'save_plots', 'plot_format', 'plot_dpi',
        'spectrum_xaxis',
        'run_eigenmode_analysis', 'eigenmode_n', 'eigenmode_top_k',
        'retarded_eigen_wavelength', 'fano_target_wavelengths',
        'svd_rank_threshold',
        'simulation_name'}


def yaml_to_flat_args(cfg: Dict[str, Any]) -> Dict[str, Any]:
    flat = dict()

    for section, kvs in cfg.items():

        if not isinstance(kvs, dict):
            continue

        for sub_key, value in kvs.items():

            mapped = _SECTION_TO_KEY.get((section, sub_key), None)

            if mapped is not None:
                flat[mapped] = value
                continue

            if section == 'extras':
                flat[sub_key] = value
                continue

            flat['{}__{}'.format(section, sub_key)] = value

    return flat


def split_flat_to_str_sim(flat: Dict[str, Any]) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    str_args = dict()
    sim_args = dict()
    leftover = dict()

    for k, v in flat.items():

        if k in _STR_FLAT_KEYS:
            str_args[k] = v
        elif k in _SIM_FLAT_KEYS:
            sim_args[k] = v
        else:
            leftover[k] = v

    if leftover:
        print_info('yaml_to_str_sim: {} unmapped keys -> sim_conf: {}'.format(
                len(leftover), sorted(leftover.keys())))
        sim_args.update(leftover)

    return str_args, sim_args


def render_args_py(args: Dict[str, Any], header: Optional[str] = None) -> str:
    lines = []

    if header is not None:
        lines.append(header)

    pp = pprint.PrettyPrinter(indent = 4, width = 100, sort_dicts = False)
    body = pp.pformat(args)
    lines.append('args = {}'.format(body))
    lines.append('')

    return '\n'.join(lines)


def convert_yaml_to_str_sim(path_yaml: str,
        path_str_out: str,
        path_sim_out: str) -> Tuple[Dict[str, Any], Dict[str, Any]]:

    with codecs.open(path_yaml, 'r', encoding = 'utf-8') as f:
        cfg = yaml.safe_load(f)

    if not isinstance(cfg, dict):
        raise ValueError(
                "[error] YAML root in <{}> is not a mapping!".format(path_yaml))

    flat = yaml_to_flat_args(cfg)
    str_args, sim_args = split_flat_to_str_sim(flat)

    str_header = '# Auto-generated by yaml_to_str_sim from <{}>'.format(path_yaml)
    sim_header = '# Auto-generated by yaml_to_str_sim from <{}>'.format(path_yaml)

    ensure_dir(os.path.dirname(os.path.abspath(path_str_out)))
    ensure_dir(os.path.dirname(os.path.abspath(path_sim_out)))

    with open(path_str_out, 'w') as f:
        f.write(render_args_py(str_args, header = str_header))

    with open(path_sim_out, 'w') as f:
        f.write(render_args_py(sim_args, header = sim_header))

    print_info('saved str_conf <{}>'.format(path_str_out))
    print_info('saved sim_conf <{}>'.format(path_sim_out))

    return str_args, sim_args


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description = (
                'Convert pymnpbem_simulation YAML config back to '
                '--str-conf / --sim-conf .py pair.'))

    parser.add_argument('input_yaml', type = str,
            help = 'Path to existing YAML config.')
    parser.add_argument('output_str', type = str,
            help = 'Output path for structure config (.py).')
    parser.add_argument('output_sim', type = str,
            help = 'Output path for simulation config (.py).')

    args = parser.parse_args(argv)

    try:
        convert_yaml_to_str_sim(args.input_yaml, args.output_str, args.output_sim)
        return 0
    except Exception as e:
        print_error('yaml_to_str_sim failed: {}'.format(e))
        return 1


if __name__ == '__main__':
    sys.exit(main())
