# Auto-generated by yaml_to_str_sim from <config/jk/dimer_auag_4nm_r0.2/auag_r0.2_g0.0.yaml>
args = {   'structure': 'connected_dimer_cube',
    'core_size': 47,
    'shell_layers': [4],
    'gap': -0.1,
    'roundings': [0.2, 0.2],
    'mesh_density': 2,
    'refine': 3,
    'materials': ['gold', 'silver'],
    'medium': 'water',
    'refractive_index_paths': {'agcl': {'type': 'constant', 'epsilon': 2.02}},
    'use_substrate': False}
