# Au@Ag@AgO generated
args = {   'base_tilt_angle': 0,
    'core_size': 47,
    'gap': 0.6,
    'materials': ['gold', 'silver', 'ago'],
    'medium': 'water',
    'mesh_density': 2,
    'offset': [0, 0, 0],
    'refine': 3,
    'refractive_index_paths': {   'ago': {   'path': '/home/yoojk20/scratch/pymnpbem_jk_config/config/jk/dimer_auagago_47_3_1_r0.2_sub/ag2o.dat',
                                             'type': 'table'},
                                  'ito': {   'epsilon': 3.8809,
                                             'type': 'constant'}},
    'rotation_angle': 0,
    'roundings': [0.2, 0.2, 0.2],
    'shell_layers': [3, 1],
    'structure': 'advanced_dimer_cube',
    'substrate': {'gap': 0.001, 'material': 'ito'},
    'tilt_angle': 0,
    'tilt_axis': [1, 0, 0],
    'use_substrate': True}
