# generated: new sim campaign (rotated / large-gap)
args = {   'base_tilt_angle': 30.0,
    'core_size': 47,
    'gap': 0.6,
    'materials': ['gold', 'silver'],
    'medium': 'water',
    'mesh_density': 2,
    'offset': [0, 0, 0],
    'refine': 3,
    'refractive_index_paths': {   'agcl': {'epsilon': 2.02, 'type': 'constant'},
                                  'ito': {   'epsilon': 3.8809,
                                             'type': 'constant'}},
    'rotation_angle': 0,
    'roundings': [0.3, 0.3],
    'shell_layers': [4],
    'structure': 'advanced_dimer_cube',
    'substrate': {'gap': 0.001, 'material': 'ito'},
    'tilt_angle': 30,
    'tilt_axis': [1, 0, 0],
    'use_substrate': True}
