output:
  name: AuAu
  dir: /home/yoojk20/research/pymnpbem/rod_aucu
  formats: [npz, json, png]
  save_plots: true
  plot_format: [png]
  plot_dpi: 300
structure:
  type: with_substrate
  base: {type: rod, diameter: 13, refine: 3, height: 37, nphi: 3, ntheta: 3, nz: 3}
  substrate: {eps: 2.25, z_position: -6.501, z_shift: 1.0}
materials:
  particle_list: [gold]
  medium: air
  refractive_index_paths: {}
  particle: gold
compute: {use_parallel: true, n_workers: 4, mirror: false, iterative: false, nonlocal: false,
  n_threads: 1, n_gpus_per_worker: 0, multi_node: false, hmode: dense}
simulation:
  type: ret_layer
  interp: curv
  waitbar: 1
  excitation: planewave
  polarizations:
  - [1, 0, 0]
  - [0, 1, 0]
  propagation_dirs:
  - [0, 0, 1]
  - [0, 0, 1]
  wavelength_range: [500, 900, 100]
  relcutoff: 3
  calculate_cross_sections: true
  enei_min: 500
  enei_max: 900
  n_wavelengths: 100
postprocess: {spectrum_xaxis: energy, run_eigenmode_analysis: false}
